"""test_detection

Revision ID: 17601ae6dfe9
Revises: 
Create Date: 2026-05-07 19:45:18.325232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '17601ae6dfe9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills_staging')
    op.drop_constraint(op.f('bill_origins_name_key'), 'bill_origins', type_='unique')
    op.create_index(op.f('ix_bill_origins_name'), 'bill_origins', ['name'], unique=True)
    op.drop_constraint(op.f('bill_sponsors_sponsor_id_fkey'), 'bill_sponsors', type_='foreignkey')
    op.drop_constraint(op.f('bill_sponsors_bill_id_fkey'), 'bill_sponsors', type_='foreignkey')
    op.create_foreign_key(None, 'bill_sponsors', 'sponsors', ['sponsor_id'], ['id'])
    op.create_foreign_key(None, 'bill_sponsors', 'bills', ['bill_id'], ['id'])
    op.drop_constraint(op.f('bill_topics_topic_id_fkey'), 'bill_topics', type_='foreignkey')
    op.drop_constraint(op.f('bill_topics_bill_id_fkey'), 'bill_topics', type_='foreignkey')
    op.create_foreign_key(None, 'bill_topics', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'bill_topics', 'bills', ['bill_id'], ['id'])
    op.alter_column('bills', 'title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('bills', 'summary',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('bills', 'hook',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('bills', 'details',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('bills_origin_id_fkey'), 'bills', type_='foreignkey')
    op.create_foreign_key(None, 'bills', 'bill_origins', ['origin_id'], ['id'])
    op.alter_column('highlights', 'title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('highlights', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('highlights_bill_id_fkey'), 'highlights', type_='foreignkey')
    op.create_foreign_key(None, 'highlights', 'bills', ['bill_id'], ['id'])
    op.drop_constraint(op.f('sponsors_name_key'), 'sponsors', type_='unique')
    op.create_index(op.f('ix_sponsors_name'), 'sponsors', ['name'], unique=True)
    op.drop_constraint(op.f('topics_name_key'), 'topics', type_='unique')
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.create_unique_constraint(op.f('topics_name_key'), 'topics', ['name'])
    op.drop_index(op.f('ix_sponsors_name'), table_name='sponsors')
    op.create_unique_constraint(op.f('sponsors_name_key'), 'sponsors', ['name'])
    op.drop_constraint(None, 'highlights', type_='foreignkey')
    op.create_foreign_key(op.f('highlights_bill_id_fkey'), 'highlights', 'bills', ['bill_id'], ['id'], ondelete='CASCADE')
    op.alter_column('highlights', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('highlights', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.create_foreign_key(op.f('bills_origin_id_fkey'), 'bills', 'bill_origins', ['origin_id'], ['id'], ondelete='SET NULL')
    op.alter_column('bills', 'details',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bills', 'hook',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bills', 'summary',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bills', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'bill_topics', type_='foreignkey')
    op.drop_constraint(None, 'bill_topics', type_='foreignkey')
    op.create_foreign_key(op.f('bill_topics_bill_id_fkey'), 'bill_topics', 'bills', ['bill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bill_topics_topic_id_fkey'), 'bill_topics', 'topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bill_sponsors', type_='foreignkey')
    op.drop_constraint(None, 'bill_sponsors', type_='foreignkey')
    op.create_foreign_key(op.f('bill_sponsors_bill_id_fkey'), 'bill_sponsors', 'bills', ['bill_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('bill_sponsors_sponsor_id_fkey'), 'bill_sponsors', 'sponsors', ['sponsor_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bill_origins_name'), table_name='bill_origins')
    op.create_unique_constraint(op.f('bill_origins_name_key'), 'bill_origins', ['name'])
    op.create_table('bills_staging',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('imported', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bills_staging_pkey'))
    )
    # ### end Alembic commands ###
