"""add_embeddings

Revision ID: 8b602cab7e98
Revises: 17601ae6dfe9
Create Date: 2026-05-07 20:17:38.090980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '8b602cab7e98'
down_revision: Union[str, Sequence[str], None] = '17601ae6dfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('embedding_jina', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.add_column('bills', sa.Column('embedding_gemma', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'embedding_gemma')
    op.drop_column('bills', 'embedding_jina')
    op.create_table('test_vector',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_vector_pkey'))
    )
    # ### end Alembic commands ###
